version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3307"

  video_creator:
    build: .
    stdin_open: true
    tty : true
    command: /startdjango
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env

  redis-stack-server:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    restart: unless-stopped


  celery:
    build: .
    command: /startceleryworker

    volumes:
      - .:/app
    depends_on:
      - redis-stack-server

